workspaceId: bdd6cc8f-9305-4bc7-9aeb-6eff68717818
workspaceName: ws-beta
expectedOracleDatabase: NCI_QA_DB
failOnUnresolvedRdlVisual: true
applyRdlVisualFix: true
applyPaginatedReportFix: true
failOnUnresolvedPaginatedReport: true
bindSemanticModelsToConnection: true
failOnUnresolvedConnectionBinding: true
bindPaginatedReportsToSemanticModels: true
failOnUnresolvedPaginatedDatasourceBinding: true
