workspaceId: 2fbd70f4-9eed-4493-b38d-106cc4c01d7c
workspaceName: ws-gamma
expectedOracleDatabase: NCI_TEST_DB
failOnUnresolvedRdlVisual: true
applyRdlVisualFix: true
applyPaginatedReportFix: true
failOnUnresolvedPaginatedReport: true
bindSemanticModelsToConnection: true
failOnUnresolvedConnectionBinding: true
bindPaginatedReportsToSemanticModels: true
failOnUnresolvedPaginatedDatasourceBinding: true
